dist: trusty
sudo: false
addons:
  chrome: stable
language: node_js
node_js: node

install:
- npm ci
cache:
  directories:
  - $HOME/.npm
script:
- npm run lint-lib
- npm run test-lib-ci
- npm run build-lib && npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist/demo
  on:
    branch: master

git:
  depth: 3
